services:
  - type: web
    name: giftme-backend
    env: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm start
    rootDir: giftme-backend
    envVars:
      - key: MONGO_URI
        value: mongodb://localhost:27017/giftme
      - key: JWT_SECRET
        value: Ado15verde
      - key: PORT
        value: 5000

  - type: web
    name: giftme-frontend
    env: static
    rootDir: giftme-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://giftme-backend.onrender.com/api
